import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Auth Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="bg-background min-h-screen flex justify-center items-center">
      {children}
    </main>
  );
}
